### PR TITLE
Update Requirement.txt

### PR DESCRIPTION
**Pull request by as3mbus**
removing re package.
adding tabulate, terminaltables, and colorclass.

which needed for client to run

Sorry if this wrong just trying to be helpful. 
cool project and i am currently trying to use this and integrate it with unity test runner

### CODE REVIEW

**Comment by msporna** [comment]
Hi, thanks for the PR and catching this! it is most certainly helpful.
One thing that I wonder about- why did you add `tabulate` module to the requirements? I don't recall using it...

**Comment by as3mbus** [comment]
umm maybe i did misunderstood and just generalize the following issue would also affect lava

gonna do another check after removing tabulate 

[random issue found from google](https://github.com/LionSec/xerosploit/issues/102)

**Comment by msporna** [comment]
Hmm seems like tabulate should be used by terminaltables under the hood...Thanks

**Comment by msporna** [comment]
This PR is not needed anymore.Requirements.txt fixed in version 3.1 of the tool.

**Pull request closed without merging**
